language: node_js

addons:
  chrome: stable

dist: xenial
services:
  - xvfb

node_js:
  - 12

install:
  - yarn

before_script:
  - yarn add chromedriver 
  - yarn add selenium-side-runner
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - yarn start  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - yarn test
