language: node_js

addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  ⋮

node_js:
  - 12

install:
  - yarn
    
script:
  - yarn test
  - yarn lint
