language: node_js

addons:
  chrome: stable

dist: xenial
services:
  - xvfb

node_js:
  - 12

install:
  - yarn

before_script:
  - "export DISPLAY=:99.0"
  - yarn start
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - yarn test
  - yarn lint
