language: node_js

addons:
  chrome: stable

dist: xenial
services:
  - xvfb

node_js:
  - 12

install:
  - yarn

before_install:
- # start your web application and listen on localhost
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=3000 http://localhost/ &
⋮

before_script:
  - yarn start
  - sleep 3 # give xvfb some time to start
  - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - yarn test
