language: node_js

addons:
  chrome: stable

dist: xenial
services:
  - xvfb

node_js:
  - 12

install:
  - yarn

before_script:
  - yarn add chromedriver 
  - yarn add selenium-side-runner

script:
  - yarn test
